services:
  api:
    command: npm run dev --workspace=apps/api
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules

  web:
    command: npm run dev --workspace=apps/web
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - .:/app
      - /app/node_modules
